
CREATE SEQUENCE account_id_seq AS  BIGINT;

CREATE TABLE account (
  id bigint GENERATED BY DEFAULT AS SEQUENCE account_id_seq PRIMARY KEY,
  name VARCHAR(30),
  watchingstream_id bigint,
  phoneNumber  VARCHAR(50),
);

CREATE SEQUENCE livestream_id_seq AS  BIGINT;

CREATE TABLE livestream (
  id bigint GENERATED BY DEFAULT AS SEQUENCE livestream_id_seq PRIMARY KEY,
  name VARCHAR(30),
  account_id bigint,
  status SMALLINT DEFAULT 0,
  isPublic BOOLEAN DEFAULT FALSE,
  pushurl  VARCHAR(1000),
  pullurl VARCHAR(1000),
  FOREIGN KEY (account_id) REFERENCES account
);

ALTER TABLE account ADD FOREIGN KEY (watchingstream_id) REFERENCES livestream (id);