
CREATE SEQUENCE account_id_seq AS  BIGINT;

CREATE TABLE account (
  id bigint GENERATED BY DEFAULT AS SEQUENCE account_id_seq PRIMARY KEY,
  name VARCHAR(30),
  phoneNumber  VARCHAR(50)
);


CREATE SEQUENCE livestream_id_seq AS  BIGINT;

CREATE TABLE livestream (
  id bigint GENERATED BY DEFAULT AS SEQUENCE livestream_id_seq PRIMARY KEY,
  name VARCHAR(30),
  status SMALLINT DEFAULT 0,
  isPublic BOOLEAN DEFAULT FALSE,
  pushurl  VARCHAR(1000),
  pullurl VARCHAR(1000)
);
